"""
class MyError raised for descriptive reasons
"""

class MyError(Exception):
    pass